### ISSUE TITLE
BHG Doesn't allow numbers in the roles

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/beaker-hostgenerator#149]
This works
Roles - `abc,def,default`

```
C:\Source\puppetlabs-powershell\powershell [MODULES-8358-add-pwsh-manager ≡]> bundle exec beaker-hostgenerator ubuntu1604-64abc,def,default.a
---
HOSTS:
  ubuntu1604-64-1:
    pe_dir:
    pe_ver:
    pe_upgrade_dir:
    pe_upgrade_ver:
    platform: ubuntu-16.04-amd64
    packaging_platform: ubuntu-16.04-amd64
    template: ubuntu-1604-x86_64
    hypervisor: vmpooler
    roles:
    - agent
    - abc
    - def
    - default
CONFIG:
  nfs_server: none
  consoleport: 443
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
```

This doesn't work
Roles - `abc,def6,default`

```
C:\Source\puppetlabs-powershell\powershell [MODULES-8358-add-pwsh-manager ≡]> bundle exec beaker-hostgenerator ubuntu1604-64abc,def6,default.a
C:/Source/puppetlabs-powershell/powershell/.bundle/windows/ruby/2.4.0/gems/beaker-hostgenerator-1.1.26/lib/beaker-hostgenerator/parser.rb:174:in `parse_node_info_token': Invalid node_info token: 64abc,def6,default.a (BeakerHostGenerator::Exceptions::InvalidNodeSpecError)
        from C:/Source/puppetlabs-powershell/powershell/.bundle/windows/ruby/2.4.0/gems/beaker-hostgenerator-1.1.26/lib/beaker-hostgenerator/generator.rb:39:in `block in generate'
        from C:/Source/puppetlabs-powershell/powershell/.bundle/windows/ruby/2.4.0/gems/beaker-hostgenerator-1.1.26/lib/beaker-hostgenerator/generator.rb:30:in `each'
        from C:/Source/puppetlabs-powershell/powershell/.bundle/windows/ruby/2.4.0/gems/beaker-hostgenerator-1.1.26/lib/beaker-hostgenerator/generator.rb:30:in `generate'
        from C:/Source/puppetlabs-powershell/powershell/.bundle/windows/ruby/2.4.0/gems/beaker-hostgenerator-1.1.26/lib/beaker-hostgenerator/cli.rb:170:in `execute'
        from C:/Source/puppetlabs-powershell/powershell/.bundle/windows/ruby/2.4.0/gems/beaker-hostgenerator-1.1.26/lib/beaker-hostgenerator/cli.rb:176:in `execute!'
        from C:/Source/puppetlabs-powershell/powershell/.bundle/windows/ruby/2.4.0/gems/beaker-hostgenerator-1.1.26/bin/beaker-hostgenerator:10:in `<top (required)>'
        from C:/Source/puppetlabs-powershell/powershell/.bundle/windows/ruby/2.4.0/bin/beaker-hostgenerator:23:in `load'
        from C:/Source/puppetlabs-powershell/powershell/.bundle/windows/ruby/2.4.0/bin/beaker-hostgenerator:23:in `<main>'
C:\Source\puppetlabs-powershell\powershell [MODULES-8358-add-pwsh-manager ≡]>
```
